ALTER TABLE "Person" ADD COLUMN "fotoDokumentId" TEXT;
ALTER TABLE "Nummernkreis" ADD COLUMN "format" TEXT NOT NULL DEFAULT '{typ}-{kuerzel}-{jahr}-{nnnn}';
ALTER TABLE "Kondition" ALTER COLUMN "ueberstundenZuschlag" SET DEFAULT 0.35;
ALTER TABLE "Kondition" ALTER COLUMN "wochenendZuschlag" SET DEFAULT 0.70;
ALTER TABLE "Kunde" ALTER COLUMN "zahlungszielTage" SET DEFAULT 0;
ALTER TYPE "VertragTyp" ADD VALUE IF NOT EXISTS 'UEBERLASSUNGSMITTEILUNG';
ALTER TYPE "VertragTyp" ADD VALUE IF NOT EXISTS 'ZUSATZVEREINBARUNG';
