ALTER TABLE "Kostenstelle"
  ADD COLUMN "provisionUeberlassung" DOUBLE PRECISION NOT NULL DEFAULT 20,
  ADD COLUMN "provisionVermittlung" DOUBLE PRECISION NOT NULL DEFAULT 50;
CREATE TYPE "EinsatzArt" AS ENUM ('UEBERLASSUNG', 'DIREKTVERMITTLUNG');
ALTER TABLE "Einsatz"
  ADD COLUMN "art" "EinsatzArt" NOT NULL DEFAULT 'UEBERLASSUNG',
  ADD COLUMN "vermittlungshonorar" DOUBLE PRECISION;
