ALTER TABLE "Kunde" ADD COLUMN "arbeitszeitmodell" TEXT, ADD COLUMN "kollektivvertrag" TEXT, ADD COLUMN "kvGueltigBis" TIMESTAMP(3), ADD COLUMN "anforderungen" TEXT, ADD COLUMN "erforderlicheQualifikationen" JSONB, ADD COLUMN "lat" DOUBLE PRECISION, ADD COLUMN "lon" DOUBLE PRECISION;
ALTER TABLE "Person" ADD COLUMN "lat" DOUBLE PRECISION, ADD COLUMN "lon" DOUBLE PRECISION, ADD COLUMN "oegkAngemeldet" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "onboarding" JSONB, ADD COLUMN "fuehrerschein" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "maxPendelKm" INTEGER;
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'KV_ABLAUF';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'PROBEZEIT_ENDE';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'UEBERNAHME_MOEGLICH';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'OEGK_ANMELDUNG';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'BEWERTUNG_OFFEN';
CREATE TABLE "KundenBewertung" ("id" TEXT NOT NULL, "kundeId" TEXT NOT NULL, "personId" TEXT NOT NULL, "einsatzId" TEXT, "datum" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "sterne" INTEGER NOT NULL, "kommentar" TEXT, "wiederArbeiten" BOOLEAN NOT NULL DEFAULT true, "quelle" TEXT NOT NULL DEFAULT 'INTERN', CONSTRAINT "KundenBewertung_pkey" PRIMARY KEY ("id"));
ALTER TABLE "KundenBewertung" ADD CONSTRAINT "KundenBewertung_kundeId_fkey" FOREIGN KEY ("kundeId") REFERENCES "Kunde"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KundenBewertung" ADD CONSTRAINT "KundenBewertung_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "BewertungsAnfrage" ("id" TEXT NOT NULL, "kundeId" TEXT NOT NULL, "personId" TEXT NOT NULL, "einsatzId" TEXT, "tokenHash" TEXT NOT NULL, "an" TEXT NOT NULL, "gultigBis" TIMESTAMP(3) NOT NULL, "erledigtAm" TIMESTAMP(3), "erstelltAm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BewertungsAnfrage_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BewertungsAnfrage_tokenHash_key" ON "BewertungsAnfrage"("tokenHash");
ALTER TABLE "BewertungsAnfrage" ADD CONSTRAINT "BewertungsAnfrage_kundeId_fkey" FOREIGN KEY ("kundeId") REFERENCES "Kunde"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BewertungsAnfrage" ADD CONSTRAINT "BewertungsAnfrage_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "Wochenstatus" ("id" TEXT NOT NULL, "personId" TEXT NOT NULL, "jahr" INTEGER NOT NULL, "kw" INTEGER NOT NULL, "status" TEXT NOT NULL, "einsatzId" TEXT, "notiz" TEXT, CONSTRAINT "Wochenstatus_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Wochenstatus_personId_jahr_kw_key" ON "Wochenstatus"("personId", "jahr", "kw");
CREATE INDEX "Wochenstatus_jahr_kw_idx" ON "Wochenstatus"("jahr", "kw");
ALTER TABLE "Wochenstatus" ADD CONSTRAINT "Wochenstatus_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "Geocode" ("key" TEXT NOT NULL, "lat" DOUBLE PRECISION NOT NULL, "lon" DOUBLE PRECISION NOT NULL, "quelle" TEXT NOT NULL DEFAULT 'nominatim', "erstelltAm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Geocode_pkey" PRIMARY KEY ("key"));
