/**
 * Volltext der AGB – aus src/vorlagen/agb-*.md erzeugt, damit die Texte im Build enthalten sind.
 * Bei Änderungen die Markdown-Datei bearbeiten und `npm run agb:build` ausführen.
 */
export const AGB_UEBERLASSUNG_MD = `# Allgemeine Geschäftsbedingungen (AGB) für die Arbeitskräfteüberlassung
Blackburn Beteiligungs GmbH (Marke „Fox & People“) · Fassung {{agb.version}} (Stand {{agb.stand}}, ersetzt die Fassung vom 19.06.2023)

## 1. Geltung
1.1. Diese AGB gelten für alle Rechtsgeschäfte zwischen Blackburn Beteiligungs GmbH, handelnd unter der Marke „Fox & People“ („Fox & People“), und einem Unternehmen, welchem Arbeitskräfte von Fox & People zur Arbeitsleistung überlassen werden („Beschäftiger“), insbesondere auch für sämtliche künftige Folge- und Zusatzbeauftragungen. Die AGB und sonstige Bestimmungen des Vertrages gelten auch dann fort, wenn Fox & People Arbeitskräfte über die ursprünglich vereinbarte oder geplante Überlassungsdauer zur Verfügung stellt, oder wenn die Anforderung von Arbeitskräften mündlich erfolgt.
1.2. Fox & People erklärt, nur aufgrund dieser AGB kontrahieren zu wollen. Allfälligen allgemeinen Vertragsbedingungen, AGB, Einkaufsbedingungen oder ähnlichem des Beschäftigers wird hiermit ausdrücklich widersprochen. Wird ausnahmsweise die Geltung anderer Vertragsbedingungen ausdrücklich und schriftlich vereinbart, so gelten deren Bestimmungen nur soweit sie nicht mit Bestimmungen dieser AGB im Widerspruch stehen. Nicht widersprechende Bestimmungen in den AGB bleiben nebeneinander bestehen.
1.3. In Rahmen- oder Einzelvereinbarungen getroffene Bestimmungen gehen diesen AGB vor, soweit sie mit den Bestimmungen dieser AGB in Widerspruch stehen; im Übrigen ergänzen diese AGB die Rahmen- oder Einzelvereinbarungen.
1.4. Maßgeblich ist die jeweils zum Zeitpunkt des Vertragsabschlusses geltende Fassung der AGB. Änderungen und Ergänzungen zu diesen AGB und zum Einzelvertrag bedürfen zu ihrer Rechtswirksamkeit der Schriftform. Dem Schriftlichkeitserfordernis genügen auch unterschriebene Dokumente, die eingescannt oder als PDF per E-Mail übermittelt werden, sowie Erklärungen, die über ein von Fox & People bereitgestelltes Kundenportal oder mittels fortgeschrittener oder qualifizierter elektronischer Signatur abgegeben werden; nicht jedoch Mitteilungen, die ohne Unterschrift per E-Mail übermittelt werden. Von diesem Schriftlichkeitsgebot kann nur schriftlich abgegangen werden.
1.5. Überlassene Arbeitskräfte sind weder zur Abgabe von Willenserklärungen noch zum Inkasso berechtigt, sofern nicht schriftlich Gegenteiliges vereinbart wird.
1.6. Vor der ersten Überlassung ist ein von beiden Seiten unterfertigter Rahmenvertrag samt Annahme dieser AGB erforderlich. Fox & People ist berechtigt, die Überlassung bis zum Vorliegen dieser Unterlagen zurückzustellen.

## 2. Vertragsabschluss und Kündigung
2.1. Angebote von Fox & People sind 7 Tage bindend, sofern diese nicht als freibleibend oder mit einem Gültigkeitsdatum bezeichnet werden. Der Vertrag kommt entweder durch Unterfertigung der Rahmen- oder Einzelvereinbarung, des Angebotes von Fox & People oder durch Auftragsbestätigung des Beschäftigers zustande. Freibleibende Angebote von Fox & People oder Angebote des Beschäftigers (Bestellungen) kommen erst durch eine entsprechende schriftliche Annahmeerklärung von Fox & People (Auftragsbestätigung) zustande. Werden diese Vertragsunterlagen vom Beschäftiger nicht unterfertigt, kommt der Vertrag auf Basis des jeweiligen Angebots von Fox & People dadurch zustande, dass die überlassenen Arbeitskräfte nach Übermittlung des Angebotes oder einer Auftragsbestätigung mit ihrem Arbeitseinsatz beginnen oder vom Beschäftiger eingesetzt werden.
2.2. Ein auf diesen AGB beruhender Überlassungsvertrag (Rahmen- oder Einzelvereinbarung) kann mangels abweichender Regelung von beiden Seiten unter Einhaltung einer Frist von 12 Wochen schriftlich zum Monatsletzten gekündigt werden. Für die Beendigung der konkreten einzelnen Überlassungen gilt Punkt 5.10.

## 3. Leistungsgegenstand
3.1. Fox & People erklärt, über eine aufrechte Berechtigung für die Ausübung des Gewerbes der Arbeitskräfteüberlassung zu verfügen.
3.2. Leistungsgegenstand ist die Zurverfügungstellung von Arbeitskräften im Sinne des Arbeitskräfteüberlassungsgesetzes („AÜG“). Fox & People schuldet weder die Erbringung bestimmter Leistungen noch einen Erfolg.
3.3. Fox & People ist berechtigt, in Vertragsunterlagen namentlich angeführte oder überlassene Arbeitskräfte jederzeit durch andere gleichwertige Personen zu ersetzen.

## 4. Honorar
4.1. Die Höhe des Honorars ergibt sich aus den unterfertigten Vertragsunterlagen, dem Angebot oder der Auftragsbestätigung von Fox & People. Werden Arbeitskräfte ohne vorheriges Angebot von Fox & People angefordert, so gilt ein angemessenes Entgelt als vereinbart.
4.2. Ändern sich nach Vertragsabschluss aufgrund gesetzlicher oder kollektivvertraglicher Anpassungen, sonstiger beim Beschäftiger geltender verbindlicher Bestimmungen allgemeiner Art oder auf Wunsch des Beschäftigers die Entlohnungsgrundlagen für die überlassenen Arbeitskräfte, ist Fox & People berechtigt, das vereinbarte Honorar rückwirkend ab dem Zeitpunkt der Entlohnungserhöhung im selben prozentuellen Ausmaß wie die Entlohnungserhöhung anzupassen. Das gilt ausdrücklich auch dann, wenn sich der für den Beschäftigerbetrieb maßgebliche Referenzlohn ändert und daher ein höherer Referenzzuschlag (§ 10 AÜG in Verbindung mit dem Kollektivvertrag für das Gewerbe der Arbeitskräfteüberlassung) zu leisten ist. Sollten Arbeitskräfte über einen vereinbarten oder voraussichtlichen Endtermin hinaus beschäftigt werden, gilt die getroffene Honorarvereinbarung auch darüber hinaus. Sollte überlassenen Arbeitskräften – auf welcher rechtlichen Grundlage auch immer – ein Anspruch auf Einmalzahlungen zustehen, ist Fox & People berechtigt, diese Einmalzahlungen dem Beschäftiger zuzüglich Lohnnebenkosten in Rechnung zu stellen.
4.3. Das Honorar ist zuzüglich der gesetzlichen Umsatzsteuer in der jeweiligen gesetzlichen Höhe, ohne jeden Abzug und spesenfrei zu bezahlen. Fox & People ist zur wöchentlichen Abrechnung berechtigt.
4.4. Die Rechnung ist bei Erhalt fällig. Wird die Rechnung nicht binnen sieben Tagen ab Zugang schriftlich und unter genauer Bezeichnung der beanstandeten Punkte beanstandet, gelten die darin verrechneten Stunden und die Höhe des Honorars als genehmigt und anerkannt.
4.5. Bei Zahlungsverzug werden 9,2 Prozentpunkte über dem Basiszinssatz, mindestens jedoch 10 % Verzugszinsen per anno, sowie die Entschädigung für Betreibungskosten nach § 458 UGB verrechnet. Die Geltendmachung eines darüber hinausgehenden Schadens bleibt vorbehalten.
4.6. Der Beschäftiger ist nicht berechtigt, Forderungen oder Ansprüche gegenüber Fox & People mit dem Überlassungshonorar aufzurechnen oder dieses zurückzubehalten, soweit nicht die Forderungen des Beschäftigers gerichtlich festgestellt wurden oder Fox & People diese schriftlich anerkannt hat.
4.7. Grundlage für die Abrechnung sind die vom Beschäftiger oder dessen Gehilfen vor Ort zumindest einmal wöchentlich zu unterschreibenden Stundennachweise oder die Auswertungen aus den elektronischen Zeiterfassungssystemen des Beschäftigers, wobei eine minutengenaue Zeitaufzeichnung mit Beginn, Ende und Pausen zu erfolgen hat (§ 26 AZG). Der Freigabe im elektronischen Kundenportal von Fox & People kommt dieselbe Wirkung zu wie einer Unterschrift auf dem Papierzettel. Werden die Stundennachweise weder vom Beschäftiger noch seinen Gehilfen unterfertigt oder freigegeben, ist Fox & People – sofern es sich um einen Einsatz bei einem Kunden des Beschäftigers handelt – berechtigt, aber nicht verpflichtet, die Stundennachweise vom Kunden des Beschäftigers unterfertigen zu lassen. Mit der Unterfertigung bzw. Freigabe der Stundennachweise durch den Beschäftiger, dessen Gehilfen oder den Kunden des Beschäftigers werden die geleisteten Stunden rechtsverbindlich festgestellt. Erfolgt keine Unterfertigung oder Freigabe, sind die Aufzeichnungen von Fox & People Basis für die Abrechnung. Die Beweislast dafür, dass die in diesen Aufzeichnungen angeführten Stunden tatsächlich nicht geleistet wurden, trägt der Beschäftiger.
4.8. Die Zeitaufzeichnungen sind vom Beschäftiger unaufgefordert einmal wöchentlich an Fox & People zu übermitteln oder im Kundenportal freizugeben. Für deren Richtigkeit und Vollständigkeit haftet der Beschäftiger. Sollten Zeitaufzeichnungen unrichtig oder unvollständig sein und Fox & People dadurch ein Schaden entstehen, verpflichtet sich der Beschäftiger, Fox & People diesbezüglich schadlos zu halten.
4.9. Unterbleibt der Einsatz von überlassenen Arbeitskräften aus Gründen, die nicht von Fox & People verschuldet worden sind, bleibt der Beschäftiger zur vollen Entgeltsleistung verpflichtet. Dies gilt auch, wenn der Beschäftiger die überlassenen Arbeitnehmer – aus welchen Gründen auch immer – nicht zur Arbeitsleistung einsetzt.
4.10. Für den Fall der Eröffnung eines Insolvenzverfahrens über das Vermögen des Beschäftigers wird bereits jetzt vereinbart, dass ab diesem Zeitpunkt eine Umstellung der Zahlungsbedingungen auf monatliche Vorauskasse erfolgt.
4.11. Die vereinbarten Preise sind – zusätzlich zu einer allfälligen Anhebung des vereinbarten Stundensatzes nach Punkt 4.2. – wertgesichert. Die Wertsicherung erfolgt nach dem von der Bundesanstalt Statistik Österreich monatlich verlautbarten Verbraucherpreisindex 2020 (VPI 2020) oder nach einem an seine Stelle tretenden Index. Ausgangsbasis für die Wertsicherung ist zunächst die für den Monat des Vertragsabschlusses errechnete Indexzahl und in der Folge jeweils die für den Monat Oktober verlautbarte Indexzahl. Der vereinbarte Preis wird erstmals im Jänner des dem Jahr des Vertragsabschlusses folgenden Jahres angepasst (ausgenommen der Vertragsabschluss erfolgte im Zeitraum Oktober bis Dezember des vorangegangenen Jahres). In der Folge erfolgt die Anpassung jeweils im Jänner eines jeden Kalenderjahres. Die für eine solche Anpassung herangezogene Indexzahl bildet sodann die Ausgangsbasis für folgende Anpassungen. Der vereinbarte Preis erhöht sich in dem Ausmaß, in dem sich die für den Monat Oktober des vorangegangenen Jahres verlautbarte Indexzahl gegenüber jener der letzten Ausgangsbasis erhöht hat. Wertsicherungsanpassungen werden jeweils im Jänner eines jeden Kalenderjahres wirksam, ohne dass es einer diesbezüglichen Erklärung durch Fox & People bedarf. Fox & People ist berechtigt, die sich aus der Indexveränderung ergebenden Beträge innerhalb der Verjährungsfrist auch rückwirkend einzufordern. Die Nichtberechnung oder Nichteinhebung gilt nicht als Verzicht.
4.12. Der Beschäftiger hat Fox & People eine gültige UID-Nummer bekannt zu geben und Änderungen unverzüglich mitzuteilen. Fox & People ist berechtigt, die UID-Nummer im Bestätigungsverfahren Stufe 2 zu überprüfen und diese Prüfung jährlich zu wiederholen.

## 5. Rechte und Pflichten des Beschäftigers
5.1. Der Beschäftiger ist verpflichtet, sämtliche gesetzliche Bestimmungen, wie zB das AÜG, ASchG, GlBG, AZG, ARG und LSD-BG sowie allenfalls anwendbare ausländische Bestimmungen zu beachten. Wird Fox & People von Arbeitskräften oder Dritten wegen Verletzung von gesetzlichen Bestimmungen in Anspruch genommen, so hält der Beschäftiger Fox & People schadlos, wenn die geltend gemachten Ansprüche auf Verstöße in der Sphäre des Beschäftigers zurückzuführen sind. Das gilt auch, wenn Fox & People gerichtliche oder verwaltungsbehördliche Strafen zu zahlen hat. Die Schadloshaltung umfasst weiters die Kosten zur zweckentsprechenden Abwehr von Ansprüchen oder Strafen, wie insbesondere Gerichts- und Rechtsanwaltskosten. Fox & People ist berechtigt, einen allenfalls erforderlichen Rechtsvertreter frei zu wählen.
5.2. Die für die Überlassung wesentlichen Informationen hat der Beschäftiger Fox & People vor deren Beginn mitzuteilen. Dazu gehören insbesondere Beginn, voraussichtliche Dauer und Ort des Arbeitseinsatzes, die benötigte Qualifikation der überlassenen Arbeitskräfte, die damit verbundene kollektivvertragliche Einstufung in den im Beschäftigerbetrieb für vergleichbare Arbeitnehmer für vergleichbare Tätigkeiten anzuwendenden Kollektivvertrag sowie die im Beschäftigerbetrieb geltenden wesentlichen Arbeits- und Beschäftigungsbedingungen, welche in verbindlichen Bestimmungen allgemeiner Art festgelegt sind und sich auf die Aspekte der Arbeitszeit und des Urlaubs beziehen. Dies gilt im Fall des § 10 Abs. 1 letzter Satz AÜG auch für verbindliche Bestimmungen allgemeiner Art, die das Entgelt betreffen. Ist in Betriebsvereinbarungen oder schriftlichen Vereinbarungen mit dem Betriebsrat des Beschäftigers die Lohnhöhe geregelt, hat der Beschäftiger dies Fox & People vor Abschluss des Vertrages schriftlich mitzuteilen. Dies gilt auch bei Akkord- oder Prämienarbeit.
5.3. Der Beschäftiger hat Fox & People auf Verlangen den für vergleichbare Stammarbeitnehmer maßgeblichen Referenzlohn samt kollektivvertraglicher Einstufung, Zulagen und Sonderzahlungen schriftlich bekannt zu geben. Unterbleibt diese Bekanntgabe oder ist sie unrichtig und entsteht Fox & People daraus ein Nachzahlungs-, Straf- oder sonstiger Schaden, hält der Beschäftiger Fox & People vollständig schadlos.
5.4. Der Beschäftiger hat Fox & People vor Beginn der Überlassung über die Leistung von Nachtschwerarbeit im Sinne des Art VII des NSchG und von Schwerarbeit im Sinne der §§ 1 bis 3 SchwerarbeitsVO zu informieren.
5.5. Die überlassenen Arbeitskräfte arbeiten nach den Anweisungen und unter Anleitung und Aufsicht des Beschäftigers. Während der Dauer der Überlassung obliegen auch dem Beschäftiger die Fürsorgepflichten des Arbeitgebers. Dies umfasst insbesondere die Arbeitnehmerschutzbestimmungen sowie die Einhaltung der Höchstgrenzen der Arbeitszeit und der Ruhezeiten.
5.6. Der Beschäftiger wird die Arbeitskräfte bei der Handhabung der Geräte und Maschinen und in die im Beschäftigerbetrieb allenfalls zusätzlich geltenden Schutzmaßnahmen einschulen und unterweisen sowie die erforderlichen Unterweisungs-, Aufklärungs- und Gefahrenabwehrmaßnahmen setzen. Schriftliche Nachweise über notwendige Einschulungen oder Unterweisungen sind Fox & People nachweislich unaufgefordert vorzulegen. Der Beschäftiger wird den überlassenen Arbeitskräften nur den gesetzlichen Vorschriften entsprechende Arbeitsmittel und Arbeitsschutzausrüstung zur Verfügung stellen. Kosten allenfalls gesetzlich vorgeschriebener oder betriebsbedingter medizinischer Untersuchungen trägt der Beschäftiger. Das Gleiche gilt für jedwede Art von Kosten für alle erforderlichen Gesundheitsnachweise und Gesundheitstests sowie allfällige vom Beschäftiger zusätzlich verlangte Unterlagen, zB Strafregisterauszüge.
5.7. Fehlzeiten einer überlassenen Arbeitskraft infolge von Arbeitsunfällen, die sich während der Dienstaufsicht bzw. der Ausübung des Direktionsrechts des Beschäftigers ereignen oder auf die Verletzung von Arbeitnehmerschutzvorschriften durch den Beschäftiger zurückzuführen sind, werden wie geleistete Arbeitszeit verrechnet.
5.8. Der Beschäftiger wird die überlassenen Arbeitskräfte nur entsprechend der vertraglich vereinbarten Qualifikation und zu dem vereinbarten Einsatz einsetzen. Er wird den überlassenen Arbeitskräften keine Anweisungen zu Tätigkeiten geben, zu denen diese nicht überlassen sind. Soweit der Beschäftiger dementgegen überlassene Arbeitskräfte zu anderen als den vereinbarten Tätigkeiten einsetzt, die zu zusätzlichen Kosten für Fox & People führen, insbesondere durch eine dadurch verursachte höhere kollektivvertragliche Einstufung, einen höheren Referenzlohn oder zusätzlich zustehende Diäten oder Zulagen, hat der Beschäftiger Fox & People schadlos zu halten. Dies umfasst auch die Kosten für eine zweckentsprechende Abwehr von Ansprüchen oder Strafen (zB Verwaltungsstrafen), insbesondere Gerichts- und Rechtsanwaltskosten. Fox & People ist berechtigt, einen allenfalls erforderlichen Rechtsvertreter frei zu wählen.
5.9. Sollte der Beschäftiger Weiterbildungsmaßnahmen setzen, die zu einer Höherqualifikation der überlassenen Arbeitskräfte führen können, oder sich Fox & People mitgeteilte Umstände ändern, wird der Beschäftiger Fox & People darüber umgehend informieren. Unterlässt der Beschäftiger eine solche Verständigung, hat er Fox & People alle daraus erwachsenden Nachteile zu ersetzen. Ergibt sich durch eine Weiterbildung eine andere Einstufung in den Kollektivvertrag des Beschäftigers oder von Fox & People, ist Fox & People berechtigt, das Honorar in demselben prozentuellen Ausmaß, in dem das Entgelt gegenüber der überlassenen Arbeitskraft anzupassen ist, ab dem Zeitpunkt der Höherqualifikation anzuheben, dies auch rückwirkend. Das gilt sinngemäß auch für den Fall, dass der Beschäftiger die überlassene Arbeitskraft für eine Tätigkeit einsetzt, die zu einer höheren Einstufung führt.
5.10. Unterlässt der Beschäftiger eine gesetzliche oder vertragliche (Informations-)Pflicht, hat er Fox & People allfällige sich daraus ergebende Schäden, Kosten oder sonstige Nachteile zur Gänze zu ersetzen.
5.11. Bei überlassenen Angestellten hat der Beschäftiger Fox & People mindestens 6 Wochen vor dem Ende einer jeden Überlassung von deren Ende schriftlich zu informieren („Rückstellfrist“). Bei überlassenen Arbeitern gelten folgende Rückstellfristen: Ab dem 2. Monat der Überlassung hat der Beschäftiger Fox & People 3 Wochen, nach 12 Monaten 4 Wochen vor Beendigung des Einsatzes schriftlich zu verständigen. Nach 18 Monaten hat der Beschäftiger Fox & People 6 Wochen, nach 2 Jahren 2 Monate, nach 5 Jahren 3 Monate und nach 15 Jahren 4 Monate vor Beendigung des Einsatzes zum Fünfzehnten oder zum Letzten des Kalendermonats schriftlich zu verständigen. Sofern der Beschäftiger die jeweils gültige Rückstellfrist nicht einhält, hat er das für die Überlassung vereinbarte Honorar auf Basis der wöchentlichen Normalarbeitszeit bis zum Ende der einzuhaltenden Rückstellfrist zu bezahlen.
5.12. Der Beschäftiger nimmt zur Kenntnis, dass er nach Ablauf des vierten Jahres einer Überlassung für die weitere Dauer der Überlassung Arbeitgeber im Sinne des Betriebspensionsgesetzes ist und daher die überlassenen Arbeitskräfte in allenfalls bestehende Betriebspensionsregelungen einzubeziehen hat.
5.13. Der Beschäftiger verarbeitet die von Fox & People übermittelten personenbezogenen Daten nur insoweit, als dies für die Erfüllung der (vor-)vertraglichen Pflichten gegenüber Fox & People sowie zur Einhaltung der gesetzlichen Pflichten unbedingt erforderlich ist. Der Beschäftiger sichert zu, dass in seinem Unternehmen die rechtlichen, technischen und organisatorischen Vorgaben des Datenschutzrechts (insbesondere DSGVO und DSG) eingehalten werden. Bei Verstößen gegen diese Bestimmungen verpflichtet sich der Beschäftiger zur Schadloshaltung von Fox & People.

## 6. Übernahmebestimmungen
6.1. Wird die überlassene Arbeitskraft während der vorgegebenen Mindesteinsatzdauer von 12 vollen Kalendermonaten vom Beschäftiger direkt oder im Betrieb des Beschäftigers über ein Unternehmen, welches im selben Geschäftsbereich wie Fox & People tätig ist (Personalbereitstellung/Arbeitskräfteüberlassung), als Arbeitnehmer oder arbeitnehmerähnliche Person in ein Vertragsverhältnis übernommen, so wird dem Beschäftiger für den entstandenen Aufwand ein angemessener Aufwandsersatz, abhängig von der bereits verstrichenen Dauer der Überlassung, in Rechnung gestellt. Dies gilt auch für den Fall, dass der Beschäftiger mit einem von Fox & People namhaft gemachten Kandidaten innerhalb von 12 Monaten nach erstmaliger Bekanntgabe des Namens einen (freien) Dienstvertrag eingeht bzw. über ein Unternehmen im selben Geschäftsbereich wie Fox & People in seinem Betrieb beschäftigt. Der Aufwandsersatz wird für den entstandenen Rekrutierungsaufwand als Personalberatungshonorar verrechnet und beträgt {{agb.uebernahmeProzent}} des Bruttojahresentgeltes auf Vollzeitbasis (bei Teilzeitbeschäftigung ist dieses auf Vollzeit hochzurechnen) der übernommenen Arbeitskraft. Die Höhe ist abhängig vom tatsächlichen Aufwand und reduziert sich pro vollem Monat der Überlassung der Arbeitskraft an den Beschäftiger vor Übernahme um jeweils 1/12, sodass bei Übernahme nach zwölf vollen Monaten Überlassungsdauer kein Ausgleich mehr zu leisten ist. Das Bruttojahresentgelt setzt sich zusammen aus dem der von Fox & People vermittelten Arbeitskraft in Aussicht gestellten bzw. mit dieser vereinbarten Bruttojahresgehalt (Fixum) zuzüglich Überstundenpauschalien und anteiliger Sonderzahlungen sowie dem Durchschnitt allfälliger Provisionen, Bonifikationen und Zulagen im ersten Dienstjahr. Das Honorar wird kaufmännisch auf die nächste Zehnerstelle gerundet. Das Mindesthonorar beträgt {{agb.uebernahmeMindest}}. Telefon- und Postspesen sind im Honorar inkludiert.
6.2. Der Beschäftiger hat Fox & People jede Übernahme im Sinne des Punktes 6.1. binnen zwei Wochen ab Abschluss des Vertragsverhältnisses schriftlich anzuzeigen und die für die Berechnung erforderlichen Entgeltdaten bekannt zu geben. Unterlässt der Beschäftiger die fristgerechte Anzeige, ist Fox & People zur Geltendmachung des doppelten zustehenden Honorars berechtigt.

## 7. Rechte und Pflichten von Fox & People
7.1. Fox & People ist zur Überprüfung der Einhaltung der Verpflichtungen des Beschäftigers berechtigt, den Ort des Arbeitseinsatzes zu betreten und erforderliche Auskünfte einzuholen.
7.2. Erscheint eine Arbeitskraft aus welchem Grund auch immer nicht am vereinbarten Einsatzort oder Arbeitsplatz, hat der Beschäftiger Fox & People hiervon umgehend in Kenntnis zu setzen. Der Beschäftiger nimmt zur Kenntnis, dass bei Erkrankung einer Arbeitskraft eine Meldung deshalb notwendig ist, damit Fox & People eine Bestätigung des Krankenversicherungsträgers oder des Gemeindearztes über Beginn, voraussichtliche Dauer und Ursache der Arbeitsunfähigkeit einholen kann. Bei Nichteinhaltung dieser Verpflichtung hat der Beschäftiger Fox & People hinsichtlich der sich daraus ergebenden Forderungen der Arbeitskraft und Dritter schadlos zu halten, zumindest jedoch jenes Entgelt zu zahlen, welches Fox & People der Arbeitskraft aufgrund und während der Dienstverhinderung zu bezahlen hat. Fox & People wird in solchen Fällen möglichst rasch eine Ersatzarbeitskraft zur Verfügung stellen.
7.3. Fox & People stellt dem Beschäftiger auf Wunsch einen Zugang zum Kundenportal zur Verfügung, über den die wöchentlichen Stundennachweise eingesehen und freigegeben sowie Rückmeldungen zu den überlassenen Arbeitskräften abgegeben werden können. Der Beschäftiger hat die Zugangsdaten vertraulich zu behandeln und ausscheidende Personen unverzüglich zu melden.

## 8. Vorzeitige Beendigung des Vertrages
8.1. Die Vertragspartner sind berechtigt, einen Vertrag über die Überlassung von Arbeitskräften vorzeitig ohne Einhaltung von Fristen oder Terminen aufzulösen, wenn ein wichtiger Grund vorliegt. Ein wichtiger Grund liegt insbesondere dann vor, wenn
a) der Beschäftiger mit einer Zahlung, zu der dieser gegenüber Fox & People verpflichtet ist, trotz Mahnung mehr als sieben Tage in Verzug ist;
b) einer der Vertragspartner trotz schriftlicher Aufforderung zur Unterlassung des anderen weiter gegen wesentliche gesetzliche oder vertragliche Bestimmungen verstößt;
c) der Beschäftiger trotz Aufforderung den Arbeitnehmerschutz- oder Fürsorgepflichten gegenüber den überlassenen Arbeitskräften nicht nachkommt;
d) Fox & People zB wegen höherer Gewalt, Krankheit oder Unfall einer oder mehrerer Arbeitskräfte keine geeignete Ersatzarbeitskraft zur Verfügung stellen kann; oder
e) gegen den Beschäftiger im Zusammenhang mit Überlassungen auf Basis dieser AGB ein Ermittlungsverfahren wegen einer Verwaltungsübertretung oder eines sonstigen Strafverfahrens – sei es, dass dieses berechtigt oder unberechtigt ist – eingeleitet wird.
8.2. Fox & People ist weiters bei Vorliegen eines wichtigen Grundes von jeder Leistungsverpflichtung befreit und zur sofortigen Zurückberufung der überlassenen Arbeitskräfte berechtigt. Hat der Beschäftiger dies zu vertreten, hat er Fox & People den daraus entstehenden Schaden zu ersetzen, so etwa das Entgelt bis zum ursprünglich beabsichtigten oder vereinbarten Überlassungsende zu bezahlen.
8.3. Wird der Vertrag aus Gründen, die in der Sphäre des Beschäftigers liegen, vorzeitig aufgelöst oder die Arbeitskräfte aus wichtigem Grund im Sinne des Punktes 8.1. von Fox & People zurückberufen, kann der Beschäftiger keine Ansprüche gegen Fox & People geltend machen.

## 9. Gewährleistung
9.1. Fox & People leistet dafür Gewähr, dass die zur Verfügung gestellten Arbeitskräfte die vertraglich ausdrücklich vereinbarte Qualifikation aufweisen; eine besondere Qualifikation der Arbeitskräfte ist nur dann geschuldet, wenn eine solche in Vertragsunterlagen ausdrücklich angeführt und von Fox & People schriftlich bestätigt worden ist, ansonsten gilt eine durchschnittliche Qualifikation als vereinbart.
9.2. Umgehend nach Beginn der Überlassung ist der Beschäftiger verpflichtet, die überlassenen Arbeitskräfte hinsichtlich fachlicher und persönlicher Qualifikation zu überprüfen. Entspricht eine überlassene Arbeitskraft der vereinbarten Qualifikation nicht, sind allfällige Mängel unter genauer Angabe dieser Fox & People umgehend, jedenfalls aber nach dem zweiten Arbeitstag schriftlich anzuzeigen, widrigenfalls sind Ansprüche wegen Gewährleistung und Schadenersatz ausgeschlossen.
9.3. Liegt ein von Fox & People zu vertretender Mangel vor und verlangt der Beschäftiger rechtzeitig Verbesserung, wird diese durch Überlassung einer Ersatzarbeitskraft innerhalb angemessener Frist erbracht.
9.4. Eine allfällige Mangelhaftigkeit hat der Beschäftiger auch in den ersten sechs Monaten ab Beginn der Überlassung nachzuweisen.
9.5. Gewährleistungs- und Schadenersatzansprüche des Beschäftigers sind bei sonstigem Verlust binnen drei Monaten gerichtlich geltend zu machen.

## 10. Haftung
10.1. Fox & People trifft keine Haftung für allfällige durch überlassene Arbeitskräfte verursachte Schäden. Fox & People haftet nicht für Verlust, Diebstahl oder Beschädigung von zur Verfügung gestellten Werkzeugen, Zeichnungen, Mustern und sonstigen übergebenen Sachen.
10.2. Vor der Inbetriebnahme von Fahrzeugen oder Geräten, für die eine Bewilligung oder Berechtigung erforderlich ist, hat der Beschäftiger das Vorhandensein der entsprechenden Berechtigungen bei den überlassenen Arbeitskräften zu überprüfen. Unterlässt der Beschäftiger diese Überprüfung, sind Ansprüche gegen Fox & People ausgeschlossen.
10.3. Fox & People haftet nicht für Schäden, die aufgrund von höherer Gewalt, Nichterscheinen am Arbeitsplatz, Krankheit oder Unfall der überlassenen Arbeitskraft entstehen. Für Folge- und Vermögensschäden, von überlassenen Arbeitskräften verursachte Schäden, Produktionsausfälle und für Pönalverpflichtungen, die der Beschäftiger zu tragen hat, ist eine Haftung von Fox & People ausgeschlossen.
10.4. Jegliche Haftung von Fox & People ist auf grobes Verschulden und Vorsatz sowie der Höhe nach auf EUR 5.000,00 beschränkt. Davon ausgenommen sind Personenschäden.

## 11. Allgemeines
11.1. Für Streitigkeiten zwischen Fox & People und dem Beschäftiger ist das sachlich in Betracht kommende Gericht am Sitz von Fox & People zuständig. Fox & People ist auch berechtigt, am allgemeinen Gerichtstand des Beschäftigers zu klagen.
11.2. Erfüllungsort für die Arbeitskräfteüberlassung und Zahlung des Beschäftigers ist der Sitz von Fox & People.
11.3. Beschäftiger und Fox & People vereinbaren die Anwendung österreichischen Rechts unter Ausschluss der Verweisungsnormen des internationalen Privatrechts (IPRG und UN-Kaufrecht).
11.4. Sollten einzelne Bestimmungen dieser AGB, einer Rahmen- oder Einzelvereinbarung unwirksam oder undurchführbar sein oder werden, wird dadurch die Gültigkeit der übrigen Bestimmungen nicht berührt. Anstatt der unwirksamen oder undurchführbaren Bestimmung vereinbaren die Vertragsteile die Geltung einer wirksamen Bestimmung, die dem wirtschaftlichen Zweck der ursprünglichen Bestimmung so weit wie möglich entspricht.
11.5. Änderungen der Firma, der Anschrift, der Rechtsform, der Bankdaten, der UID-Nummer oder anderer für die Überlassung relevanter Informationen hat der Beschäftiger Fox & People umgehend schriftlich bekannt zu geben. Gibt der Beschäftiger derartige Änderungen nicht bekannt und gehen ihm deshalb rechtlich bedeutsame Erklärungen von Fox & People nicht zu (insbesondere Rechnungen, Mahnungen, Kündigungsschreiben, Vertragsänderungen), gelten diese dennoch als zugegangen. Das Risiko für die verzögerte oder unterbliebene Zustellung trägt in diesem Fall der Beschäftiger. Fox & People ist berechtigt, alle Erklärungen an die zuletzt bekannt gegebene E-Mail-Adresse des Beschäftigers zu übermitteln.
11.6. Informationen zur Verarbeitung personenbezogener Daten durch Fox & People sowie zu den Betroffenenrechten sind unter {{firma.email}} erhältlich.
`;

export const AGB_VERMITTLUNG_MD = `# Allgemeine Geschäftsbedingungen (AGB) für die Arbeitskräftevermittlung
Blackburn Beteiligungs GmbH (Marke „Fox & People“) · Fassung {{agb.version}} (Stand {{agb.stand}}, ersetzt die Fassung vom 19.06.2023)

## 1. Geltung
1.1. Diese AGB gelten für alle Rechtsgeschäfte zwischen Blackburn Beteiligungs GmbH, handelnd unter der Marke „Fox & People“ („Fox & People“), und einem Unternehmen („Kunde“), welchem Fox & People Leistungen betreffend Personalberatung, Personalsuche, Recruiting, Personalvermittlung oder vergleichbare Dienstleistungen erbringt (Verträge über solche Dienstleistungen werden folgend als „Vertrag“ bezeichnet), insbesondere auch für sämtliche künftige Folge- und Zusatzbeauftragungen.
1.2. Der Inhalt dieser AGB bildet einen integrierenden Bestandteil des jeweiligen Vertrages. Fox & People erklärt, nur aufgrund dieser AGB kontrahieren zu wollen. Allfälligen allgemeinen Vertragsbedingungen, AGB, Einkaufsbedingungen oder ähnlichem des Kunden wird hiermit ausdrücklich widersprochen. Wird ausnahmsweise die Geltung anderer Vertragsbedingungen ausdrücklich und schriftlich vereinbart, so gelten deren Bestimmungen nur soweit sie nicht mit Bestimmungen dieser AGB im Widerspruch stehen. Nicht widersprechende Bestimmungen in den AGB bleiben nebeneinander bestehen.
1.3. In Angeboten, Auftragsbestätigungen oder Verträgen getroffene Bestimmungen gehen diesen AGB vor, soweit sie mit den Bestimmungen dieser AGB in Widerspruch stehen; im Übrigen ergänzen diese AGB die Offerte, Auftragsbestätigungen oder Verträge.
1.4. Maßgeblich ist die jeweils zum Zeitpunkt des Vertragsabschlusses geltende Fassung der AGB. Änderungen und Ergänzungen zu diesen AGB und zum jeweiligen Vertrag bedürfen zu ihrer Rechtswirksamkeit der Schriftform. Dem Schriftlichkeitserfordernis genügen auch unterschriebene Dokumente, die eingescannt oder als PDF per E-Mail übermittelt werden, sowie Erklärungen mittels fortgeschrittener oder qualifizierter elektronischer Signatur; nicht jedoch Mitteilungen, die ohne Unterschrift per E-Mail übermittelt werden. Von diesem Schriftlichkeitsgebot kann nur schriftlich abgegangen werden.

## 2. Vertragsabschluss und Kündigung
2.1. Angebote von Fox & People sind 7 Tage bindend, sofern diese nicht als freibleibend oder mit einem Gültigkeitsdatum bezeichnet werden. Der Vertrag kommt entweder durch Unterfertigung des Angebotes von Fox & People oder durch Auftragsbestätigung des Kunden zustande. Freibleibende Angebote von Fox & People oder Angebote des Kunden (Bestellungen) kommen erst durch eine entsprechende schriftliche Annahmeerklärung von Fox & People (Auftragsbestätigung) zustande.
2.2. Werden diese Vertragsunterlagen vom Kunden nicht unterfertigt, kommt der Vertrag auf Basis des jeweiligen Angebots von Fox & People dadurch zustande, dass Fox & People auf Basis der jeweiligen Informationen des Kunden – insbesondere Anforderungsprofile und/oder Stellenbeschreibungen – mit der Personalsuche oder -auswahl beginnt.
2.3. Der Vertrag kann von jeder Partei aus wichtigem Grund vorzeitig aufgelöst werden, ohne dass dabei Fristen oder Termine einzuhalten sind. Ein wichtiger Grund für die sofortige Auflösung liegt insbesondere dann vor, wenn der Kunde mit einer Zahlung, zu der er gegenüber Fox & People verpflichtet ist, trotz Mahnung mehr als 7 Tage in Verzug gerät oder ein Vertragspartner trotz schriftlicher Aufforderung des anderen zur Unterlassung weiterhin wesentliche gesetzliche oder vertragliche Bestimmungen verletzt.
2.4. Wird der Vertrag aus Gründen, die in der Sphäre des Kunden liegen, vorzeitig aufgelöst oder unterbleibt der erfolgreiche Abschluss des Auftrages (etwa das Eingehen eines Dienstverhältnisses eines Bewerbers mit dem Kunden) aus derartigen Gründen, kann der Kunde keine Ansprüche gegen Fox & People geltend machen und Fox & People hat mangels abweichender schriftlicher Vereinbarung Anspruch auf 80 Prozent des vereinbarten Honorars.

## 3. Leistungsgegenstand
3.1. Fox & People erklärt, über eine aufrechte Berechtigung für die Ausübung des Gewerbes der Arbeitsvermittlung zu verfügen.
3.2. Der jeweilige Leistungsgegenstand (etwa die Vermittlung von Arbeitskräften) ergibt sich aus dem Vertrag, aus der Auftragsbestätigung oder dem Offert von Fox & People.
3.3. Die Leistungserbringung durch Fox & People erfolgt nach den Grundsätzen ordnungsgemäßer Berufsausübung. Die fachlichen und persönlichen Eigenschaften der Kandidaten werden sorgfältig geprüft. Fox & People wird sich redlich darum bemühen, dass Kandidaten jene Kenntnisse und Fähigkeiten aufweisen, die einem Anforderungsprofil bzw. einer Stellenbeschreibung möglichst entsprechen. Fox & People übernimmt keine Gewährleistung oder Haftung für bestimmte Kenntnisse, Fähigkeiten oder Qualifikationen der Kandidaten. Wurden zur Qualifikation des Kandidaten keine besonderen Vereinbarungen getroffen, gilt eine durchschnittliche Qualifikation als vereinbart.
3.4. Sollte es nach Begründung eines Beschäftigungsverhältnisses zwischen einem Kandidaten und dem Kunden zu einer Auflösung von diesem kommen, findet eine Nachbesetzung von Kandidaten durch Fox & People nur nach neuerlichem und zu honorierendem Auftrag statt.
3.5. Fox & People kann nicht garantieren, dass ein vorgeschlagener Kandidat nicht auch anderweitig platziert wird und/oder sich dieser Kandidat für einen anderen Arbeitgeber entscheidet. Ansprüche des Kunden gegen Fox & People sind diesfalls ausgeschlossen.

## 4. Honorar
4.1. Die Höhe des Honorars ergibt sich aus den unterfertigten Vertragsunterlagen, dem Angebot oder der Auftragsbestätigung von Fox & People. Die Höhe des Honorars ist abhängig von der zu besetzenden Stelle und der erforderlichen Qualifikation.
4.2. Eine erfolgreiche Personalvermittlung liegt vor, wenn zwischen dem Kandidaten und dem Kunden ein Beschäftigungsverhältnis begründet wird.
4.3. Basis für die Berechnung des Vermittlungshonorars ist das erste jährliche Bruttoentgelt des vermittelten Kandidaten inklusive aller variablen Entgeltsanteile wie insbesondere Gratifikationen, Gewinnbeteiligungen, Provisionen, Überstundenpauschalen und sonstigen Zulagen; alternativ das im Offert genannte Honorar. **Mangels abweichender Vereinbarung beträgt das Honorar {{agb.vermittlungProzent}} des jährlichen Bruttoentgelts, mindestens jedoch {{agb.uebernahmeMindest}}.** Wird kein Bruttoentgelt genannt, berechnet sich das Honorar anhand eines angemessenen Bruttojahresentgelts für vergleichbare Arbeitnehmer am geplanten Arbeitsort. Der Kunde ist verpflichtet, Fox & People umgehend die für die korrekte Berechnung des Honorars erforderlichen Daten bekanntzugeben.
4.4. Der Anspruch auf das Honorar entsteht unabhängig davon, ob eine Beschäftigung des Kandidaten in Vollzeit, Teilzeit, als freier Mitarbeiter, im Rahmen einer Überlassung durch ein drittes Unternehmen oder in irgendeiner anderen vom Gesetz erlaubten Form beim Kunden erfolgt. Das jährliche Bruttoentgelt ist bei Teilzeitbeschäftigung und jeder sonstigen Art der Beschäftigung auf Vollzeit hochzurechnen.
4.5. Sollte ein Kandidat für eine andere als die ursprünglich mitgeteilte Position eingestellt werden, kommt Fox & People ebenfalls ein Anspruch auf das Honorar nach den vorgenannten Grundsätzen zu. Gleiches gilt für den Fall, dass ein Beschäftigungsverhältnis zwischen einem mit dem Kunden rechtlich oder wirtschaftlich verbundenen Unternehmen („Konzern“) oder vom Kunden namhaft gemachten Dritten und einem von Fox & People namhaft gemachten Kandidaten zustande kommt.
4.6. Sofern keine abweichende Vereinbarung getroffen wird, entsteht der Honoraranspruch in zwei gleichen Teilen, wobei der erste Teilbetrag bei Abschluss des Vertrages zwischen dem Kandidaten und dem Kunden und der zweite Teilbetrag bei Arbeitsbeginn des Kandidaten fällig wird.
4.7. Der Honoraranspruch entsteht auch dann, wenn innerhalb von 12 Monaten nach Namhaftmachung des Kandidaten durch Fox & People ein Beschäftigungsverhältnis zwischen dem Kandidaten und dem Kunden oder einem Dritten gemäß Punkt 4.5. zustande kommt. Der Kunde verpflichtet sich, Fox & People jegliche Art der Beschäftigung spätestens binnen 2 Wochen ab Begründung des Dienstverhältnisses (oder eines anderen Vertragsverhältnisses im Sinne des Punktes 4.4.) schriftlich anzuzeigen. Es gelten in jedem Fall die Zahlungsbedingungen des Punktes 6. Unterlässt der Kunde die fristgerechte Anzeige einer Beschäftigung an Fox & People, ist Fox & People zur Geltendmachung des doppelten zustehenden Honorars berechtigt.
4.8. Macht Fox & People gegenüber dem Kunden einen Kandidaten namhaft, der sich vor der Namhaftmachung bereits unabhängig von der Tätigkeit von Fox & People beim Kunden beworben hat, so hat der Kunde Fox & People darüber unverzüglich, längstens binnen fünf Arbeitstagen, zu informieren und die frühere Bewerbung nachzuweisen. Unterlässt der Kunde diese Information, gilt der Kandidat als von Fox & People namhaft gemacht.
4.9. Fox & People ist berechtigt, im Zusammenhang mit der Dienstleistung anfallende Aufwendungen, wie insbesondere Reisekosten (zB Kilometergeld, Bahntickets, Flugkosten, Hotelkosten etc.), dem Kunden neben dem Honorar nach tatsächlichem Aufwand in Rechnung zu stellen.
4.10. Vom Kunden zusätzlich gewünschte oder von Fox & People für zweckmäßig erachtete Inseratschaltungen und vergleichbare Leistungen werden zuzüglich Abgaben und Steuern in Rechnung gestellt und sind unabhängig vom erfolgreichen Abschluss der Dienstleistung bei Rechnungserhalt zu begleichen.
4.11. Der Kunde anerkennt die Angemessenheit des vereinbarten Honorars und verzichtet auf die Anfechtung des Vertrages wegen Irrtums, Verkürzung über die Hälfte oder anderer Rechtsgründe, soweit zulässig.
4.12. Der Kunde ist nicht berechtigt, Forderungen oder Ansprüche gegenüber Fox & People mit dem Honorar aufzurechnen oder dieses zurückzubehalten, sofern solche Forderungen des Kunden nicht gerichtlich festgestellt oder von Fox & People schriftlich anerkannt wurden.

## 5. Rechte und Pflichten des Kunden
5.1. Die für die Kandidatenauswahl wesentlichen Informationen hat der Kunde Fox & People bei Auftragserteilung bekanntzugeben. Dazu gehören insbesondere Beginn, voraussichtliche Dauer und Ort des Arbeitseinsatzes, die benötigte Qualifikation, die vorgesehene Dotierung der zu besetzenden Position sowie die damit verbundene kollektivvertragliche Einstufung in den im Kundenbetrieb für vergleichbare Arbeitnehmer für vergleichbare Tätigkeiten anzuwendenden Kollektivvertrag. Der Kunde gewährleistet die Richtigkeit und Vollständigkeit der Informationen.
5.2. Unterlässt der Kunde eine gesetzliche oder vertragliche (Informations-)Pflicht, hat er Fox & People sämtliche sich daraus ergebenden Schäden, Kosten oder wie auch immer geartete Nachteile in vollem Umfang zu ersetzen.
5.3. Der Kunde ist verpflichtet, die Eignung und Qualifikation der von Fox & People vorgeschlagenen oder namhaft gemachten Kandidaten zu prüfen. Der Kunde trägt die alleinige Verantwortung für die Auswahl des jeweiligen Kandidaten.
5.4. Der Kunde hat Fox & People eine gültige UID-Nummer bekannt zu geben und Änderungen unverzüglich mitzuteilen.

## 6. Zahlungsbedingungen
6.1. Mangels abweichender Vereinbarungen sind Rechnungen bei Erhalt fällig.
6.2. Das Vermittlungshonorar ist zuzüglich Umsatzsteuer in der jeweiligen gesetzlichen Höhe ohne jeden Abzug und spesenfrei zu bezahlen.
6.3. Wird eine Rechnung nicht binnen 7 Tagen ab Zugang schriftlich und unter substantiierter Darlegung der beanstandeten Punkte gerügt, gelten die darin verrechneten Leistungen und die Höhe des Honorars als genehmigt und anerkannt.
6.4. Bei Zahlungsverzug werden 9,2 Prozentpunkte über dem Basiszinssatz, mindestens jedoch 10 % Verzugszinsen per anno, sowie die Entschädigung für Betreibungskosten nach § 458 UGB vereinbart. Die Geltendmachung eines darüber hinausgehenden Schadens bleibt vorbehalten.

## 7. Haftung
7.1. Die von Fox & People durchgeführte Personalvermittlung ersetzt nicht die eingehende Prüfung des Kandidaten durch den Kunden. Durch Begründung eines Beschäftigungsverhältnisses zwischen dem Kunden und dem vorgeschlagenen Kandidaten bestätigt der Kunde die vertragskonforme Leistungserbringung durch Fox & People. Die alleinige Verantwortung für die getroffene Auswahl sowie für die zukünftige Leistungserbringung durch den Kandidaten liegt beim Kunden.
7.2. Fox & People übernimmt keine Haftung für durch vermittelte Kandidaten verursachte Schäden, es sei denn, diese sind nachweislich und direkt durch vorsätzliche Fehlangaben oder vorsätzliches Verschweigen durch Fox & People entstanden.
7.3. Fox & People haftet nicht für die vom Kunden getroffene Auswahl eines Kandidaten sowie für das Vorliegen der arbeits- und aufenthaltsrechtlichen Bewilligungen, die allenfalls notwendig sind, um im Unternehmen des Kunden tätig werden zu können. Fox & People haftet nicht und übernimmt keine Gewährleistung für die Richtigkeit der von Kandidaten gemachten Angaben und übermittelten Unterlagen, insbesondere betreffend deren Qualifikation.
7.4. Jegliche Haftung von Fox & People ist jedenfalls auf grobes Verschulden und Vorsatz sowie der Höhe nach auf EUR 5.000,00 beschränkt. Davon ausgenommen sind Personenschäden.
7.5. Gewährleistungs- und Schadenersatzansprüche des Kunden sind bei sonstigem Verfall binnen sechs Monaten gerichtlich geltend zu machen.

## 8. Geheimhaltung und Datenschutz
8.1. Fox & People verpflichtet sich, vom Kunden mitgeteilte Informationen und zur Verfügung gestellte Unterlagen vertraulich zu behandeln und nur im Rahmen der erteilten Aufträge zu verwenden. Fox & People und der Kunde verpflichten sich zur gegenseitigen Verschwiegenheit über alle im Zusammenhang mit der Auftragsabwicklung zur Kenntnis gelangten Informationen und Umstände, insbesondere zur Geheimhaltung der Geschäftsgeheimnisse des Vertragspartners.
8.2. Der Kunde ist verpflichtet, über die persönlichen und beruflichen Verhältnisse der ihm vorgestellten Kandidaten Stillschweigen zu bewahren. Referenzauskünfte dürfen nur nach vorheriger schriftlicher Genehmigung durch Fox & People erfolgen, um den Persönlichkeitsschutz der Kandidaten sicherzustellen.
8.3. Der Kunde verpflichtet sich, sämtliche personenbezogenen Daten namhaft gemachter oder vermittelter Kandidaten streng vertraulich zu behandeln. Insbesondere verpflichtet er sich, diese Daten unter keinen Umständen an Dritte weiterzugeben oder Dritten namhaft zu machen. Verstößt der Kunde gegen diese Verpflichtung, gilt eine verschuldensunabhängige Konventionalstrafe in der Höhe des zweifachen Honorars als vereinbart, die mit Geltendmachung durch Fox & People fällig wird. Darüber hinausgehende Ansprüche von Fox & People, etwa auf Unterlassung oder Ersatz eines darüber hinausgehenden Schadens, bleiben vorbehalten.
8.4. Fox & People übermittelt dem Kunden personenbezogene Daten zur Erfüllung der beauftragten Leistungen. Der Kunde verpflichtet sich in diesem Zusammenhang zur Einhaltung der Bestimmungen des DSG und der DSGVO und zur Mitwirkung hinsichtlich der Wahrung der Rechte der Betroffenen. Personenbezogene Daten, die zu keinem Vertragsverhältnis geführt haben, sind nach Beendigung des Auftrags bzw. nach Ablauf der gesetzlichen Aufbewahrungs- oder Speicherfristen vom Kunden unverzüglich zu löschen. Der Kunde hält Fox & People schadlos, sollte Fox & People von Dritten wegen Verletzung datenschutzrechtlicher Bestimmungen in Anspruch genommen werden.
8.5. Informationen zur Verarbeitung personenbezogener Daten durch Fox & People sowie zu den Betroffenenrechten sind unter {{firma.email}} erhältlich.

## 9. Allgemeines
9.1. Für Streitigkeiten zwischen Fox & People und dem Kunden ist das sachlich in Betracht kommende Gericht am Sitz von Fox & People zuständig. Fox & People ist auch berechtigt, am allgemeinen Gerichtstand des Kunden zu klagen.
9.2. Erfüllungsort für die Arbeitskräftevermittlung und Zahlung des Kunden ist der Sitz von Fox & People.
9.3. Kunde und Fox & People vereinbaren die Anwendung österreichischen Rechts unter Ausschluss der Verweisungsnormen des internationalen Privatrechts (IPRG und UN-Kaufrecht).
9.4. Sollten einzelne Bestimmungen dieser AGB oder eines Vertrages zwischen Kunde und Fox & People unwirksam oder undurchführbar sein oder werden, wird dadurch die Gültigkeit der übrigen Bestimmungen nicht berührt. Anstatt der unwirksamen oder undurchführbaren Bestimmung vereinbaren die Vertragsteile die Geltung einer wirksamen Bestimmung, die dem wirtschaftlichen Zweck der ursprünglichen Bestimmung so weit wie möglich entspricht.
9.5. Änderungen der Firma, der Anschrift, der Rechtsform, der Bankdaten, der UID-Nummer oder anderer für die Erfüllung des Vertrages relevanter Informationen hat der Kunde Fox & People umgehend schriftlich bekannt zu geben. Gibt der Kunde derartige Änderungen nicht bekannt und gehen ihm deshalb rechtlich bedeutsame Erklärungen von Fox & People nicht zu (insbesondere Rechnungen, Mahnungen, Kündigungsschreiben, Vertragsänderungen), gelten diese dennoch als zugegangen. Das Risiko für die verzögerte oder unterbliebene Zustellung trägt in diesem Fall der Kunde. Fox & People ist berechtigt, alle Erklärungen an die zuletzt bekannt gegebene E-Mail-Adresse des Kunden zu übermitteln.
`;
