CREATE TYPE "AbwesenheitStatus" AS ENUM ('BEANTRAGT', 'GENEHMIGT', 'ABGELEHNT');
ALTER TABLE "Abwesenheit" ADD COLUMN "status" "AbwesenheitStatus" NOT NULL DEFAULT 'GENEHMIGT', ADD COLUMN "quelle" TEXT, ADD COLUMN "dokumentId" TEXT, ADD COLUMN "entschiedenVon" TEXT, ADD COLUMN "entschiedenAm" TIMESTAMP(3);
CREATE TABLE "AppLogin" ("id" TEXT NOT NULL, "personId" TEXT NOT NULL, "codeHash" TEXT NOT NULL, "gultigBis" TIMESTAMP(3) NOT NULL, "versuche" INTEGER NOT NULL DEFAULT 0, "erstelltAm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AppLogin_pkey" PRIMARY KEY ("id"), CONSTRAINT "AppLogin_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "AppLogin_personId_idx" ON "AppLogin"("personId");
CREATE TABLE "Nachricht" ("id" TEXT NOT NULL, "personId" TEXT NOT NULL, "vonMitarbeiter" BOOLEAN NOT NULL, "text" TEXT NOT NULL, "nutzerName" TEXT, "gelesenAm" TIMESTAMP(3), "erstelltAm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Nachricht_pkey" PRIMARY KEY ("id"), CONSTRAINT "Nachricht_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "Nachricht_personId_erstelltAm_idx" ON "Nachricht"("personId", "erstelltAm");
CREATE TYPE "NachweisStatus" AS ENUM ('EINGEREICHT', 'BESTAETIGT', 'ABGELEHNT');
CREATE TABLE "Stundennachweis" ("id" TEXT NOT NULL, "personId" TEXT NOT NULL, "einsatzId" TEXT, "jahr" INTEGER NOT NULL, "kw" INTEGER NOT NULL, "tage" JSONB NOT NULL, "summe" DOUBLE PRECISION NOT NULL, "notiz" TEXT, "fotoDokumentId" TEXT, "status" "NachweisStatus" NOT NULL DEFAULT 'EINGEREICHT', "rueckmeldung" TEXT, "eingereichtAm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "geprueftAm" TIMESTAMP(3), "geprueftVon" TEXT, CONSTRAINT "Stundennachweis_pkey" PRIMARY KEY ("id"), CONSTRAINT "Stundennachweis_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Stundennachweis_personId_jahr_kw_key" ON "Stundennachweis"("personId", "jahr", "kw");
CREATE TYPE "EmpfehlungStatus" AS ENUM ('NEU', 'KONTAKTIERT', 'EINGESTELLT', 'PRAEMIE_FAELLIG', 'AUSBEZAHLT', 'ABGELEHNT');
CREATE TABLE "Empfehlung" ("id" TEXT NOT NULL, "werberId" TEXT NOT NULL, "name" TEXT NOT NULL, "telefon" TEXT, "email" TEXT, "notiz" TEXT, "status" "EmpfehlungStatus" NOT NULL DEFAULT 'NEU', "empfohlenePersonId" TEXT, "praemieBetrag" DOUBLE PRECISION, "eingestelltAm" TIMESTAMP(3), "faelligAm" TIMESTAMP(3), "ausbezahltAm" TIMESTAMP(3), "erstelltAm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Empfehlung_pkey" PRIMARY KEY ("id"), CONSTRAINT "Empfehlung_werberId_fkey" FOREIGN KEY ("werberId") REFERENCES "Person"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Empfehlung_empfohlenePersonId_fkey" FOREIGN KEY ("empfohlenePersonId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE INDEX "Empfehlung_werberId_idx" ON "Empfehlung"("werberId");
ALTER TABLE "Person" ADD COLUMN "notfallkontakt" TEXT, ADD COLUMN "appZuletztAktiv" TIMESTAMP(3), ADD COLUMN "profilBestaetigtAm" TIMESTAMP(3);
ALTER TABLE "Dokument" ADD COLUMN "geprueft" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "quelle" TEXT;
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'STUNDENNACHWEIS_PRUEFEN';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'KRANKMELDUNG';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'URLAUBSANTRAG';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'DOKUMENT_PRUEFEN';
ALTER TYPE "AufgabeTyp" ADD VALUE IF NOT EXISTS 'EMPFEHLUNG_PRAEMIE';
